name: scrape mercari
on: [push]
# on:
#   schedule:
#     - cron: "*/10 * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: create env file
        run: |
          touch .env
          echo EMAIL =${{ secrets.EMAIL }} >> .env
          echo PASSWORD =${{ secrets.PASSWORD }} >> .env
      - run: npm install
      - run: npm run start
